module Twarog.Frontend.NameGen 
  ( 
    NameRace (..)
    , names
    , filterNames
  ) 
where

import Data.Text as T
import Data.List as L
import Twarog.Backend.Types (Sex (..))

data NameState = RandomName 
                | UserName 

data NameRace = Dwarvish
              | Other
              deriving (Show, Eq)

filterNames :: Text -> [(Text, Sex, NameRace)]
                      -- (name, sex, race) 
filterNames str = 
  let
    quest = L.nub $ T.unpack $ T.toLower str
    doContain :: Text -> Char -> Bool
    doContain n x = elem x $ L.nub $ T.unpack $ T.toLower n
  in
    L.filter (\(n, s, r) -> and (L.map (doContain n) quest)) names


names :: [(Text, Sex, NameRace)]
names = (className Female Other womanNames)
         ++ ( className Male Other manNames )
         ++ ( className Female Dwarvish dwarfWomanNames )
         ++ ( className Male Dwarvish dwarfManNames )

className :: Sex -> NameRace -> [Text]-> [(Text, Sex, NameRace)]
className s nr list = 
  let 
    clasify n = (n, s, nr) 
  in
    Prelude.map clasify list

dwarfWomanNames :: [Text]
dwarfWomanNames = 
  let 
    change :: String -> Text
    change (x:xs) | elem x ['r', 'n', 'i', 'e'] = T.pack $ (Prelude.reverse xs) ++ "ja"
                  | otherwise = T.empty
  in
    Prelude.map (change . Prelude.reverse . T.unpack) dwarfManNames
    
womanNames :: [Text]
womanNames = [
  "Aburia", 
  "Acamasa", 
  "Accia", 
  "Acilia", 
  "Adaloalda", 
  "Adamaira", 
  "Adelaide", 
  "Aebutia", 
  "Aedinia", 
  "Aelia", 
  "Agaþia", 
  "Agelmunda", 
  "Agenaricha", 
  "Agenora", 
  "Agilmunda", 
  "Agilulfa", 
  "Aililla", 
  "Ainstulfa", 
  "Airgetmara", 
  "Alahisa", 
  "Alalia", 
  "Albatia", 
  "Alboina", 
  "Alcibiadesa", 
  "Aldihoca", 
  "Algauta", 
  "Allectia", 
  "Alluwamna", 
  "Alpîna", 
  "Amatia", 
  "Ambrosia", 
  "Ammuna", 
  "Anarawda", 
  "Anitta", 
  "Annia", 
  "Anspranda", 
  "Api", 
  "Appuleia", 
  "Aquillia", 
  "Archelocha", 
  "Archytasa", 
  "Argimpasa", 
  "Arimna", 
  "Arioalda", 
  "Ariperta", 
  "Aristarcha", 
  "Arnuwanda", 
  "Arria", 
  "Arsinia", 
  "Arta", 
  "Artoria", 
  "Ascarica", 
  "Asinia", 
  "Asistaea", 
  "Ateia", 
  "Atilia", 
  "Atrea", 
  "Atria", 
  "Atria", 
  "Atronia", 
  "Audoina", 
  "Aufidia", 
  "Aula", 
  "Aureliana", 
  "Auþaria", 
  "Axia", 
  "Babudia", 
  "Baebia", 
  "Balventia", 
  "Bantia", 
  "Berngala", 
  "Betiliena", 
  "Blaga", 
  "Blagoslaa", 
  "Blandia", 
  "Bleddyna", 
  "Blossia", 
  "Bogumila", 
  "Boglaa", 
  "Boguwolaa", 
  "Bohdana", 
  "Boreslaa", 
  "Bozena", 
  "Bratomira", 
  "Bresa", 
  "Bresala", 
  "Brideia", 
  "Brigantia", 
  "Bronislaa", 
  "Bucculeia", 
  "Burebista", 
  "Butautasa", 
  "Byrþnoþa", 
  "Cadwaladra", 
  "Cadwallona", 
  "Caecia", 
  "Caeparia", 
  "Caesia", 
  "Calavia", 
  "Calchasa", 
  "Calisia", 
  "Camilia", 
  "Canidia", 
  "Cania", 
  "Canutia", 
  "Capna", 
  "Caristania", 
  "Carvilia", 
  "Cassiopeia", 
  "Catantîna", 
  "Cechta", 
  "Ceionia", 
  "Cenabetia", 
  "Cerediga", 
  "Cermna", 
  "Cesina", 
  "Chararica", 
  "Childreica", 
  "Chloderica", 
  "Chlodewica", 
  "Chlodomira", 
  "Chlodoswinþa", 
  "Chnodomara", 
  "Chociemira", 
  "Chroca", 
  "Chvaliboga", 
  "Cicolli", 
  "Ciltrama", 
  "Cinâeda", 
  "Cincia", 
  "Ciniocha", 
  "Cinioda", 
  "Claffoa", 
  "Clepha", 
  "Clevsina", 
  "Clovisa", 
  "Clytaemnestra", 
  "Cogidubna", 
  "Coiedia", 
  "Cominia", 
  "Comosica", 
  "Cona", 
  "Conalla", 
  "Conmâela", 
  "Connala", 
  "Connla", 
  "Conona", 
  "Cosona", 
  "Coþela", 
  "Coventina", 
  "Crimþanna", 
  "Crouga", 
  "Cuilla", 
  "Cunincperta", 
  "Cunobelina", 
  "Curtia", 
  "Cia", 
  "Cwichelma", 
  "Cynana", 
  "Cynewulfa", 
  "Dagasa", 
  "Dapixa", 
  "Decebala", 
  "Decenea", 
  "Decumia", 
  "Delbâeþa", 
  "Demoloeona", 
  "Desideria", 
  "Dexsia", 
  "Dicomesa", 
  "Didia", 
  "Dioclesa", 
  "Dobrina", 
  "Dobroboga", 
  "Domnalla", 
  "Donau", 
  "Dossenia", 
  "Dragoboga", 
  "Dresta", 
  "Dromichaeta", 
  "Duala", 
  "Dui", 
  "Dura", 
  "Ebera", 
  "Ecgbalda", 
  "Ecgwine", 
  "Egnatia", 
  "Electra", 
  "Eleni", 
  "Eochaida", 
  "Eôgana", 
  "Epidia", 
  "Epulona", 
  "Equitia", 
  "Era", 
  "Eriomona", 
  "Eþriela", 
  "Euclida", 
  "Eurymacha", 
  "Fadia", 
  "Faenia", 
  "Faildergdôita", 
  "Faleria", 
  "Favonia", 
  "Felsina", 
  "Fercorba", 
  "Fergna", 
  "Ferona", 
  "Fiacha", 
  "Finnachta", 
  "Floria", 
  "Fodbgena", 
  "Fredegara", 
  "Fufia", 
  "Fundana", 
  "Gaea", 
  "Galana", 
  "Galeria", 
  "Gambara", 
  "Ganna", 
  "Garibalda", 
  "Gede", 
  "Gegania", 
  "Gelimerica", 
  "Genanna", 
  "Genobauda", 
  "Genserica", 
  "Gerainta", 
  "Gestiblinda", 
  "Gibulda", 
  "Girica", 
  "Gizura", 
  "Godehoca", 
  "Godeperta", 
  "Godiva", 
  "Gordia", 
  "Gostomysla", 
  "Grabosa", 
  "Granna", 
  "Grattia", 
  "Greine", 
  "Grimualsa", 
  "Grufudda", 
  "Gunderica", 
  "Gundomada", 
  "Gunþamunda", 
  "Haeþcyna", 
  "Haminga", 
  "Haragunda", 
  "Hariobauda", 
  "Harmonia", 
  "Heardreda", 
  "Helma", 
  "Helvia", 
  "Hepa", 
  "Hermunda", 
  "Herugrima", 
  "Hervarda", 
  "Hesioda", 
  "Hildepranda", 
  "Hilderica", 
  "Hippolyta", 
  "Hirtia", 
  "Hortara", 
  "Hortensia", 
  "Hoseidia", 
  "Hreþela", 
  "Hyacinþa", 
  "Hygelaca", 
  "Hypatia", 
  "Hywela", 
  "Icara", 
  "Icilia", 
  "Icovellauns", 
  "Idomenea", 
  "Idrisa", 
  "Idwala", 
  "Indutiomara", 
  "Instenia", 
  "Iphigenia", 
  "Iriela", 
  "Irna", 
  "Izyaslaa", 
  "Jarmila", 
  "Jaroslaa", 
  "Jocasta", 
  "Junia", 
  "Juodikisa", 
  "Juventia", 
  "Labarna", 
  "Labenia", 
  "Laberia", 
  "Labraida", 
  "Ladislaa", 
  "Laelia", 
  "Laetoria", 
  "Lafrensia", 
  "Laigne", 
  "Lampronia", 
  "Lantachara", 
  "Laodamasa", 
  "Leofwina", 
  "Leþuca", 
  "Leutfreda", 
  "Leuþaria", 
  "Licinia", 
  "Ligeikisa", 
  "Liutperta", 
  "Liutpranda", 
  "Ljuba", 
  "Llywellyna", 
  "Longinia", 
  "Loreia", 
  "Lucceia", 
  "Luccilia", 
  "Lucretia", 
  "Lugaida", 
  "Luga", 
  "Luigne", 
  "Lutatia", 
  "Lycurga", 
  "Macrinia", 
  "Macrobia", 
  "Maecilia", 
  "Maelgwynedda", 
  "Maelia", 
  "Magnachara", 
  "Makriana", 
  "Mallia", 
  "Manlia", 
  "Marcomera", 
  "Maredudda", 
  "Martiana", 
  "Matia", 
  "Medea", 
  "Medericha", 
  "Medericha", 
  "Memmia", 
  "Menelaa", 
  "Menþva", 
  "Merfyna", 
  "Merogaisa", 
  "Merovecha", 
  "Metona", 
  "Milonia", 
  "Minatia", 
  "Mindaugasa", 
  "Minicia", 
  "Misa", 
  "Moskona", 
  "Mucia", 
  "Muimne", 
  "Muinemôna", 
  "Muiredacha", 
  "Munia", 
  "Mutina", 
  "Myslibora", 
  "Naevia", 
  "Nasennia", 
  "Nechtana", 
  "Nemeda", 
  "Nemetoria", 
  "Nepia", 
  "Netona", 
  "Nia", 
  "Nicandera", 
  "Nicanora", 
  "Nigidia", 
  "Nigilia", 
  "Nipia", 
  "Nodensa", 
  "Novia", 
  "Nuada", 
  "Nula", 
  "Numeria", 
  "Odomira", 
  "Oedipa", 
  "Oenga", 
  "Olcinia", 
  "Olloma", 
  "Onuista", 
  "Oppia", 
  "Opsia", 
  "Orania", 
  "Orba", 
  "Orestesa", 
  "Orolesa", 
  "Oslaca", 
  "Ostromira", 
  "Otacilia", 
  "Owaina", 
  "Palpellia", 
  "Pamba", 
  "Parma", 
  "Pedia", 
  "Perctarita", 
  "Persna", 
  "Perna", 
  "Pescennia", 
  "Petellia", 
  "Petronia", 
  "Phaeþona", 
  "Pharamounda", 
  "Philona", 
  "Pinnesa", 
  "Piscia", 
  "Piþama", 
  "Piytia", 
  "Plautia", 
  "Pleurata", 
  "Pleuriasa", 
  "Plikiene", 
  "Plotia", 
  "Polyba", 
  "Polynicesa", 
  "Pompilia", 
  "Pomponia", 
  "Popidia", 
  "Portia", 
  "Priama", 
  "Priaria", 
  "Procla", 
  "Pupia", 
  "Pupluna", 
  "Parruma", 
  "Quinctilia", 
  "Quinctia", 
  "Rabiria", 
  "Radogosta", 
  "Radovita", 
  "Raginperta", 
  "Ragnachara", 
  "Rastimira", 
  "Rastislaa", 
  "Ratchisa", 
  "Ratislaa", 
  "Ravena", 
  "Rhemaxa", 
  "Rhicomeresa", 
  "Rhodria", 
  "Rholesa", 
  "Rhysa", 
  "Ricchara", 
  "Rigna", 
  "Rinnala", 
  "Rioþama", 
  "Rodoalda", 
  "Rostislaa", 
  "Roþaria", 
  "Rubobostesa", 
  "Rudraige", 
  "Rufria", 
  "Ruma", 
  "Rutilia", 
  "Ryngaudasa", 
  "Sabicia", 
  "Saena", 
  "Salvia", 
  "Scorilla", 
  "Scribonia", 
  "Seia", 
  "Selyfa", 
  "Sempronia", 
  "Senganna", 
  "Sentia", 
  "Sepunia", 
  "Sequana", 
  "Sergia", 
  "Sestia", 
  "Setna", 
  "Sextilia", 
  "Shava", 
  "Sidonia", 
  "Sigerica", 
  "Sigoberta", 
  "Silia", 
  "Sirna", 
  "Sirona", 
  "Sivinbudasa", 
  "Slâine", 
  "Slanonna", 
  "Slavisa", 
  "Sobairce", 
  "Socellia", 
  "Sophoclesa", 
  "Spina", 
  "Sprudeikisa", 
  "Spuria", 
  "Spurtia", 
  "Statia", 
  "Statna", 
  "Steksysa", 
  "Suana", 
  "Sucella", 
  "Suedia", 
  "Suleviae", 
  "Sulis", 
  "Suomara", 
  "Suppoluliuma", 
  "Surina", 
  "Svetoboga", 
  "Tabiti", 
  "Tadia", 
  "Talorca", 
  "Talorgana", 
  "Talþybia", 
  "Tamara", 
  "Tancreda", 
  "Tarana", 
  "Tarchuna", 
  "Tatoa", 
  "Telemacha", 
  "Tercia", 
  "Tettia", 
  "Tezlaa", 
  "Tigernmasa", 
  "Titia", 
  "Treblana", 
  "Tremellia", 
  "Tuccia", 
  "Tudhaliya", 
  "Tulara", 
  "Ulpia", 
  "Umbrenia", 
  "Uncilina", 
  "Unicha", 
  "Unioegosta", 
  "Ura", 
  "Urgulania", 
  "Ursicina", 
  "Uurada", 
  "Vadomara", 
  "Vaefara", 
  "Vagennia", 
  "Valamira", 
  "Varia", 
  "Vatinia", 
  "Vatluna", 
  "Vedia", 
  "Veia", 
  "Velcala", 
  "Veleslaa", 
  "Velia", 
  "Velsnasa", 
  "Velsysa", 
  "Vembutasa", 
  "Verecundia", 
  "Vesnia", 
  "Vestralpa", 
  "Vibia", 
  "Victricia", 
  "Vikina", 
  "Vikintasa", 
  "Vilikaila", 
  "Vipsania", 
  "Viridomara", 
  "Viria", 
  "Viseikisa", 
  "Vismantasa", 
  "Visula", 
  "Viþicaba", 
  "Vitruvia", 
  "Vlada", 
  "Vlasta", 
  "Voislaa", 
  "Voja", 
  "Volaginia", 
  "Volodymyra", 
  "Volennia", 
  "Volena", 
  "Volia", 
  "Vorena", 
  "Vortigerna", 
  "Vyacheslaa", 
  "Wachoa", 
  "Waltaria", 
  "Wiglafa", 
  "Willehari", 
  "Wisimara", 
  "Wislaa", 
  "Wulfomira", 
  "Wulfstana", 
  "Xenophona", 
  "Ybora", 
  "Yngwina", 
  "Zalmodegica", 
  "Zelimira", 
  "Zenoe", 
  "Zidanta", 
  "Zvezdana", 
  "Zyraxa"
  ]

manNames = [
  "Agenor",
  "Agilmund",
  "Agilulfus",
  "Ailill",
  "Ainstulfus",
  "Airgetmar",
  "Alahisus",
  "Alalius",
  "Albatius",
  "Alboinus",
  "Alcibiades",
  "Alcyone",
  "Aldihocus",
  "Algaut",
  "Allectius",
  "Alluwamn",
  "Alpîn",
  "Amatius",
  "Ambrosius",
  "Ammun",
  "Anarawd",
  "Anaxagoras",
  "Anaximandros",
  "Anitt",
  "Annius",
  "Ansprandus",
  "Api",
  "Appuleius",
  "Aquillius",
  "Hâvamâl",
  "Archelochus",
  "Archytas",
  "Argimpas",
  "Arimnus",
  "Arioaldus",
  "Aripertus",
  "Aristarchus",
  "Arnuwand",
  "Arrius",
  "Arsinius",
  "Art",
  "Artorius",
  "Ascaric",
  "Asinius",
  "Asistaeus",
  "Ateius",
  "Atilius",
  "Atreus",
  "Atrius",
  "Atrius",
  "Atronius",
  "Audoinus",
  "Aufidius",
  "Aulus",
  "Aurelianus",
  "Auþari",
  "Axius",
  "Babudius",
  "Baebius",
  "Balventius",
  "Bantius",
  "Bato",
  "Berngal",
  "Betilienus",
  "Biksys",
  "Blag",
  "Blago",
  "Blagoslaus",
  "Blandius",
  "Bleddyn",
  "Blossius",
  "Bogumil",
  "Boguslaus",
  "Boguwola",
  "Bohdan",
  "Boreslaus",
  "Borivoi",
  "Borvo",
  "Bozen",
  "Bratomir",
  "Bres",
  "Bresal",
  "Brideia",
  "Brigantius",
  "Britomaris",
  "Bronislaus",
  "Bucculeius",
  "Burebist",
  "Butautas",
  "Buteikis",
  "Byrþnoþ",
  "Cadwaladr",
  "Cadwallon",
  "Caecius",
  "Caeparius",
  "Caesius",
  "Calavius",
  "Calchas",
  "Calisius",
  "Callirrhoe",
  "Camilius",
  "Canidius",
  "Canius",
  "Canutius",
  "Capnus",
  "Caristanius",
  "Carvilius",
  "Cassiopeia",
  "Caustantîn",
  "Cecht",
  "Ceionius",
  "Cenabetius",
  "Ceredig",
  "Cermn",
  "Cesinus",
  "Chararic",
  "Childeric",
  "Childreica",
  "Chloderic",
  "Chlodewic",
  "Chlodomir",
  "Chlodoswinþa",
  "Chnodomar",
  "Chociemir",
  "Chrocus",
  "Chrocusa",
  "Chvalibog",
  "Cicollius",
  "Ciltrama",
  "Cinâed",
  "Cincius",
  "Cingetorix",
  "Cinioch",
  "Ciniod",
  "Claffous",
  "Clephus",
  "Clevsinus",
  "Clodio",
  "Clovisa",
  "Clytaemnestra",
  "Cogidubnus",
  "Coiedius",
  "Cominius",
  "Comosic",
  "Con",
  "Conall",
  "Conmâel",
  "Connal",
  "Connl",
  "Conon",
  "Coson",
  "Coþel",
  "Cotiso",
  "Coventin",
  "Crimþann",
  "Crino",
  "Croug",
  "Cuill",
  "Cunincpert",
  "Cunobelinusa",
  "Curtius",
  "Cusius",
  "Cwichelm",
  "Cynan",
  "Cynewulf",
  "Dagas",
  "Danae",
  "Dapix",
  "Daugirutis",
  "Daujotas",
  "Dausprungas",
  "Decebal",
  "Decenea",
  "Decumius",
  "Delbâeþ",
  "Demoloeon",
  "Desiderius",
  "Dexsius",
  "Dicomes",
  "Didius",
  "Diocles",
  "Diogenes",
  "Diomedes",
  "Dobrina",
  "Dobrobog",
  "Domnall",
  "Donau",
  "Dossenius",
  "Dragobog",
  "Drest",
  "Dromichaet",
  "Dual",
  "Dubhtolargg",
  "Dui",
  "Dumnorix",
  "Dur",
  "Eber",
  "Ecgbald",
  "Ecgwin",
  "Egnatius",
  "Electra",
  "Eleni",
  "Empedocles",
  "Eochaid",
  "Eocho",
  "Eôgan",
  "Epidius",
  "Epulon",
  "Equitius",
  "Era",
  "Erdvilas",
  "Eriomona",
  "Eteocles",
  "Eþriel",
  "Euclid",
  "Eucripides",
  "Eurydice",
  "Eurymachus",
  "Fadius",
  "Faenius",
  "Faildergdôit",
  "Falerius",
  "Favonius",
  "Felsinus",
  "Fercorb",
  "Fergna",
  "Feron",
  "Fiach",
  "Fiachu",
  "Finnacht",
  "Florius",
  "Fodbgen",
  "Fredegar",
  "Fufius",
  "Fundanus",
  "Gaea",
  "Galan",
  "Galerius",
  "Gambar",
  "Gann",
  "Garibaldus",
  "Gartnait",
  "Gede",
  "Gedvilas",
  "Geganius",
  "Gelimerica",
  "Genann",
  "Genobaud",
  "Genseric",
  "Geraint",
  "Gestiblindus",
  "Gibuld",
  "Giric",
  "Gizur",
  "Glaukias",
  "Gobannos",
  "Godehocus",
  "Godepertus",
  "Godigisiel",
  "Godiva",
  "Goitosyros",
  "Gordius",
  "Gostomysl",
  "Grabos",
  "Grannus",
  "Grattius",
  "Greine",
  "Grimualsus",
  "Grines",
  "Grufudd",
  "Gunderic",
  "Gundomad",
  "Gunþamund",
  "Haeþcyn",
  "Haming",
  "Hantili",
  "Haragund",
  "Hariobaud",
  "Harmonius",
  "Hattusili",
  "Heardred",
  "Helianþe",
  "Helicaon",
  "Helm",
  "Helvius",
  "Hepus",
  "Heraclides",
  "Hermione",
  "Hermund",
  "Herugrim",
  "Hervard",
  "Hesiod",
  "Hicetas",
  "Hildeprand",
  "Hilderic",
  "Hippolytus",
  "Hirtius",
  "Hortar",
  "Hortensius",
  "Hoseidius",
  "Hreþel",
  "Hyacinþ",
  "Hygelac",
  "Hypati",
  "Hywel",
  "Iago",
  "Ianþe",
  "Icarus",
  "Icilius",
  "Icovellauns",
  "Idomeneus",
  "Idris",
  "Idwal",
  "Inarime",
  "Indutiomar",
  "Instenius",
  "Iphidamas",
  "Iphigenius",
  "Irereo",
  "Iriel",
  "Irnus",
  "Ismene",
  "Izyaslaus",
  "Jarmil",
  "Jaroslaus",
  "Jocast",
  "Junius",
  "Juodikis",
  "Juventius",
  "Kintibutas",
  "Kitenis",
  "Kruto",
  "Labarn",
  "Labenius",
  "Laberius",
  "Labraid",
  "Ladislaus",
  "Laelius",
  "Laetorius",
  "Lafrensius",
  "Laigne",
  "Lamissio",
  "Lampronius",
  "Lantachara",
  "Laodamas",
  "Leofwin",
  "Leþucus",
  "Leutfred",
  "Leuþari",
  "Liamicho",
  "Licinius",
  "Ligeikis",
  "Liutpertus",
  "Liutprandus",
  "Ljuba",
  "Llywellyn",
  "Longinius",
  "Loreius",
  "Lucceius",
  "Luccilius",
  "Lucretius",
  "Lugaidus",
  "Lugus",
  "Luigne",
  "Lutatius",
  "Lycurgus",
  "Macrinius",
  "Macrobius",
  "Maecilius",
  "Maelgwynedda",
  "Maelius",
  "Magnachara",
  "Makrian",
  "Mallius",
  "Mallobaudes",
  "Manlius",
  "Marcomer",
  "Maredudd",
  "Martianus",
  "Matius",
  "Medea",
  "Mederich",
  "Medericha",
  "Melpomene",
  "Memmius",
  "Menelaus",
  "Menþvus",
  "Merfyn",
  "Merogaisa",
  "Merovech",
  "Meton",
  "Milonius",
  "Minatius",
  "Mindaugas",
  "Minicius",
  "Misus",
  "Moskon",
  "Mucius",
  "Muimne",
  "Muinemôn",
  "Muiredach",
  "Munius",
  "Mursili",
  "Mutinus",
  "Muwatalli",
  "Myslibor",
  "Naevius",
  "Narce",
  "Nasennius",
  "Nechtan",
  "Nemedus",
  "Nemetorius",
  "Nepete",
  "Nepius",
  "Neton",
  "Nia",
  "Nicander",
  "Nicanor",
  "Nigidius",
  "Nigilius",
  "Nipius",
  "Nodens",
  "Novius",
  "Nuada",
  "Nulus",
  "Numerius",
  "Odomir",
  "Oedipus",
  "Oengus",
  "Olcinius",
  "Ollom",
  "Onuist",
  "Oppius",
  "Opsius",
  "Oranius",
  "Orba",
  "Orestes",
  "Orgetorix",
  "Oroles",
  "Oslac",
  "Ostromir",
  "Otacilius",
  "Owain",
  "Palpellius",
  "Pamba",
  "Papaios",
  "Parmus",
  "Pedius",
  "Perctaritus",
  "Pericles",
  "Persnus",
  "Perusnus",
  "Pescennius",
  "Petellius",
  "Petronius",
  "Phaeþon",
  "Pharamound",
  "Philon",
  "Pinnes",
  "Piscius",
  "Piþam",
  "Piyusti",
  "Plautius",
  "Pleuratus",
  "Pleurias",
  "Plikiene",
  "Plotius",
  "Polybus",
  "Polynices",
  "Pompilius",
  "Pomponius",
  "Popidius",
  "Portius",
  "Priam",
  "Priarius",
  "Proclus",
  "Pupius",
  "Puplunus",
  "Pusarrum",
  "Quinctilius",
  "Quinctius",
  "Rabirius",
  "Radogost",
  "Radovit",
  "Raginpertus",
  "Ragnachar",
  "Rando",
  "Rastimir",
  "Rastislaus",
  "Ratchisus",
  "Ratislaus",
  "Ravenus",
  "Rhemaxa",
  "Rhicomeres",
  "Rhodri",
  "Rholes",
  "Rhys",
  "Ricchar",
  "Rign",
  "Rinnala",
  "Rioþamus",
  "Rodoaldus",
  "Rostislaus",
  "Roþarius",
  "Rubobostes",
  "Rudraige",
  "Rufrius",
  "Rumus",
  "Rutilius",
  "Ryngaudas",
  "Sabicius",
  "Saenus",
  "Salvius",
  "Scorill",
  "Scribonius",
  "Seius",
  "Selyf",
  "Sempronius",
  "Sengann",
  "Sentius",
  "Sepunius",
  "Sequan",
  "Sergius",
  "Sestius",
  "Setnus",
  "Sextilius",
  "Shavus",
  "Sidonius",
  "Sigeric",
  "Sigobert",
  "Silius",
  "Sirn",
  "Siron",
  "Sivinbudas",
  "Slâine",
  "Slanonn",
  "Slavis",
  "Sobairce",
  "Socellius",
  "Sophocles",
  "Spinus",
  "Sprudeikis",
  "Spurius",
  "Spurtius",
  "Statius",
  "Statnus",
  "Steksys",
  "Suanus",
  "Sucellus",
  "Suedius",
  "Suleviae",
  "Sulis",
  "Suomar",
  "Suppolulium",
  "Surinus",
  "Suþri",
  "Svelgaitis",
  "Svetobog",
  "Tabiti",
  "Tadius",
  "Takiah",
  "Talorc",
  "Talorgan",
  "Talþybius",
  "Tamara",
  "Tancreda",
  "Taran",
  "Tarchunus",
  "Tatous",
  "Telemachus",
  "Telepinu",
  "Tercius",
  "Tettius",
  "Tezlaus",
  "Tigernmas",
  "Titius",
  "Toutatis",
  "Treblanus",
  "Tremellius",
  "Tuccius",
  "Tudhaliy",
  "Tularus",
  "Ulpius",
  "Umbrenius",
  "Uncilin",
  "Unichus",
  "Unioegost",
  "Ur",
  "Urgulanius",
  "Ursicin",
  "Uurad",
  "Vadomar",
  "Vaefar",
  "Vagennius",
  "Valamir",
  "Varius",
  "Vatinius",
  "Vatlunus",
  "Vedius",
  "Veius",
  "Velaþri",
  "Velcalus",
  "Veleslaus",
  "Velius",
  "Velsnasus",
  "Velsys",
  "Vembutas",
  "Verecundius",
  "Vesnius",
  "Vestralp",
  "Vibius",
  "Victricius",
  "Vikin",
  "Vikintas",
  "Vilikail",
  "Vipsanius",
  "Viridomarus",
  "Virius",
  "Viseikis",
  "Vismantas",
  "Visulus",
  "Viþicab",
  "Vitruvius",
  "Vlad",
  "Vlast",
  "Voislaus",
  "Voj",
  "Volaginius",
  "Volodymyr",
  "Volusennius",
  "Volusenus",
  "Volusius",
  "Vorenus",
  "Vortigern",
  "Vyacheslaus",
  "Wachous",
  "Waltari",
  "Wiglaf",
  "Willehari",
  "Wisimar",
  "Wislaus",
  "Wulfomir",
  "Wulfstan",
  "Xenophon",
  "Ybor",
  "Yngwin",
  "Zalmodegic",
  "Zelimir",
  "Zeno",
  "Zidant",
  "Zvezdan",
  "Zyrax"
  ]

dwarfManNames :: [Text]
dwarfManNames = [
  "Ái"
  , "Alfr"
  , "Ánarr"
  , "Andvari"
  , "Ánn"
  , "Aurvangr"
  , "Austri"
  , "Báfurr"
  , "Bari"
  , "Bávör"
  , "Bívör"
  , "Bívurr"
  , "Bláinn"
  , "Blindvið"
  , "Blövurr"
  , "Brokkr"
  , "Brúni"
  , "Bumburr"
  , "Bömburr"
  , "Dagfinnr"
  , "Dáinn"
  , "Dolgr"
  , "Dólgþrasir"
  , "Dólgþvari"
  , "Dóri"
  , "Dúfr"
  , "Dulinn"
  , "Durinn"
  , "Durnir"
  , "Dvalinn"
  , "Eikinskjaldi"
  , "Eitri"
  , "Fáinn"
  , "Falr"
  , "Fár" 
  , "Farli"
  , "Fiδr"
  , "Fili"
  , "Finnr"
  , "Fjalarr"
  , "Fjölsviðr"
  , "Fornbogi"
  , "Frár"
  , "Frór"
  , "Frosti"
  , "Fræger"
  , "Fulangr"
  , "Fundinn"
  , "Förvi"
  , "Galarr"
  , "Gandalfr"
  , "Ginnarr"
  , "Glói"
  , "Glóinn"
  , "Grerr"
  , "Grimr"
  , "Gullmævill"
  , "Hannarr"
  , "Hár"
  , "Haugspori"
  , "Haur"
  , "Heftifili"
  , "Hepti"
  , "Heri"
  , "Hildingr"
  , "Hleðjólfr"
  , "Hlévangr"
  , "Hljóðólfr"
  , "Hornbori"
  , "Hugstari"
  , "Högstari"
  , "Íri"
  , "Ívaldi"
  , "Jaki"
  , "Jari"
  , "Kíli"
  , "Litr"
  , "Ljómi"
  , "Lofarr"
  , "Lóinn"
  , "Lóni"
  , "Miðviðr"
  , "Mjöðvitnir"
  , "Mjöklituðr"
  , "Munin"
  , "Nabbi"
  , "Náinn"
  , "Náli"
  , "Nár"
  , "Nefi"
  , "Niði"
  , "Nífenger"
  , "Nípingr"
  , "Norðri"
  , "Nóri"
  , "Nýr"
  , "Nýráðr"
  , "Næfr"
  , "Óinn"
  , "Ónarr"
  , "Óri"
  , "Ráðsvinnr"
  , "Reggin"
  , "Rekkr"
  , "Siarr"
  , "Sindri"
  , "Skáfiðr"
  , "Skávær"
  , "Skirfi"
  , "Suðri"
  , "Svíarr"
  , "Svíurr"
  , "Tigvi"
  , "Þekkr"
  , "Þjóðrørir"
  , "Þorinn"
  , "Þráinn"
  , "Þrár"
  , "Þrór"
  , "Þrasir"
  , "Þróinn"
  , "Uni"
  , "Uri"
  , "Varr"
  , "Veigr"
  , "Veggr"
  , "Vestri"
  , "Vifir"
  , "Vili"
  , "Vilir"
  , "Vindalfr"
  , "Virfir"
  , "Vitr"
  , "Ölni"
  , "Önn"
  ]

